// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxjmNsEWrcps18XrSjmEIbCA7LcORQ0os',
    appId: '1:605658079942:web:1afc1f6df0ff3ea8aa6dc7',
    messagingSenderId: '605658079942',
    projectId: 'user-sphere',
    authDomain: 'user-sphere.firebaseapp.com',
    storageBucket: 'user-sphere.appspot.com',
    measurementId: 'G-DM0VHR3TD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD75ShjdWrbz4slNVrJZucCptndeLGMYEg',
    appId: '1:605658079942:android:dc2b667568e4981aaa6dc7',
    messagingSenderId: '605658079942',
    projectId: 'user-sphere',
    storageBucket: 'user-sphere.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC175DWKnOPGh_wYSlCYE_Dy4-Na9KXPYo',
    appId: '1:605658079942:ios:872e2047432326ffaa6dc7',
    messagingSenderId: '605658079942',
    projectId: 'user-sphere',
    storageBucket: 'user-sphere.appspot.com',
    iosBundleId: 'com.example.userSphere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC175DWKnOPGh_wYSlCYE_Dy4-Na9KXPYo',
    appId: '1:605658079942:ios:872e2047432326ffaa6dc7',
    messagingSenderId: '605658079942',
    projectId: 'user-sphere',
    storageBucket: 'user-sphere.appspot.com',
    iosBundleId: 'com.example.userSphere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxjmNsEWrcps18XrSjmEIbCA7LcORQ0os',
    appId: '1:605658079942:web:af6cf278dd9c938faa6dc7',
    messagingSenderId: '605658079942',
    projectId: 'user-sphere',
    authDomain: 'user-sphere.firebaseapp.com',
    storageBucket: 'user-sphere.appspot.com',
    measurementId: 'G-ML1XS7KLYX',
  );
}
